/** Umbrella header mirroring libDaisy's daisy.h for the CHOMPI desktop simulator. */
#pragma once
#ifndef DSY_LIBDAISY_H
#define DSY_LIBDAISY_H
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
#include "daisy_core.h"
#include "sys/system.h"
#include "sys/dma.h"
#include "per/gpio.h"
#include "per/tim.h"
#include "per/tim_channel.h"
#include "per/i2c.h"
#include "per/sai.h"
#include "per/uart.h"
#include "per/sdmmc.h"
#include "hid/audio.h"
#include "hid/switch.h"
#include "hid/logger.h"
#include "hid/MidiEvent.h"
#include "hid/midi_parser.h"
#include "hid/usb_midi.h"
#include "hid/midi.h"
#include "dev/sr_4021.h"
#include "sys/fatfs.h"
#include "util/FIFO.h"
#include "util/Stack.h"
#include "util/ringbuffer.h"
#include "util/color.h"
#include "util/wav_format.h"
#include "util/scopedirqblocker.h"
#include "ui/UiEventQueue.h"
#include "ui/UI.h"
#include "ui/PotMonitor.h"
#endif
